#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : ConsensusSemantics  # The title of the book. Will be placed in the left navbar.
author                      : ConsensusSemantics # The author of the book
copyright                   : "2024"  # Copyright year to be placed in the footer
logo                        : semantique.png  # A path to the book logo
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
bibtex_bibfiles:
   - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year
    
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

# HTML-specific settings
html:
  #favicon: 'images/logo/favicon.ico' # A path to a favicon image
  use_edit_page_button: true # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button: true # Whether to add a link to your repository button
  use_issues_button: true # Whether to add an "open an issue" button
  home_page_in_navbar: false # Whether to include your home page in the left Navigation Bar
  comments:
    hypothesis: true
    utterances: false

# Launch button settings
launch_buttons:
  notebook_interface: classic # The interface interactive links will activate ["classic", "jupyterlab"]
  thebe: false # Add a thebe button to pages (requires the repository to run on Binder)

repository:
  url: https://github.com/ConsensusSemantics/consensus_wiki # The URL to your book's repository
  path_to_book: 'https://github.com/ConsensusSemantics/consensus_wiki' # A path to your book's folder, relative to the repository root.
  branch: master # Which branch of the repository should be used when creating links